Repository UWQSC/algorithmic-trading, pull requests merged in 2025-02, with the labels that each got.

#45 Added Param Patel member_list.txt
  member_list.txt
Labels: Ready for Review, Ready for Merge

#46 githubmemberonboard/25
  member_list.txt
Labels: Ready for Merge

#47 added Harsimar Kaur to member_list.
  member_list.txt
Labels: Ready for Review, Ready for Merge

#48 On boarding - Sandeep Kumar
  member_list.txt
Labels: Ready for Merge

#50 Added sample interface and implementation
  .github/workflows/test.yml
  Makefile
  interfaces/__init__.py
  interfaces/sample_interface.py
  src/sample_impl.py
  tests/sample_test.py
Labels: Ready for Review, Ready for Merge

#49 Added "Kamal Kandpal" to member_list.txt
  member_list.txt
Labels: Ready for Review, Ready for Merge

#51 [topic/#20] - Added Manan Jain to the member list
  member_list.txt
Labels: Ready for Merge

#54 Added Aryan Patel to member list
  member_list.txt
Labels: Ready for Merge

#55 Github Member Onboarding [Lena Ye]
  member_list.txt
Labels: Ready for Review, Ready for Merge

#58 make a folder for data collection
  data/data.sample
  src/common/__init__.py
  src/common/config.py
  src/common/data_collection.py
  tests/common/__init__.py
  tests/common/data_collection_test.py
Labels: Ready for Review

#59 Added Tra Luu to member list
  member_list.txt
Labels: Ready for Review, Ready for Merge
