Repository UWQSC/algorithmic-trading, pull requests merged in 2025-03, with the labels that each got.

#68 Added a Preprocessor Interface python file to interfaces.
  interfaces/preprocessor_interface.py
Labels: Ready for Merge

#69 Implementing Simple Moving Average
  .github/workflows/pylint.yml
  .idea/algorithmic-trading.iml
  .idea/misc.xml
  .idea/other.xml
  interfaces/algorithms/__init__.py
  interfaces/algorithms/algorithm_interface.py
  interfaces/preprocessing/__init__.py
  interfaces/preprocessing/preprocessor_interface.py
  interfaces/preprocessor_interface.py
  interfaces/sample_interface.py
  requirements.txt
  src/algorithms/__init__.py
  src/algorithms/simple_moving_average_impl.py
  src/common/config.py
  src/preprocessing/__init__.py
  src/preprocessing/sma_preprocessor_impl.py
  tests/algorithms/__init__.py
  tests/algorithms/simple_moving_average_impl_test.py
  tests/preprocessing/__init__.py
  tests/preprocessing/sma_preprocessor_impl_test.py
Labels: Ready for Review

#72 Setup the files for HMM tasks
  src/algorithms/hidden_markov_model_impl.py
  src/preprocessing/hma_preprocessor_impl.py
  tests/algorithms/hidden_markov_model_impl_test.py
  tests/preprocessing/hmm_preprocessor_impl_test.py
  tests/preprocessing/sma_preprocessor_impl_test.py
Labels: Ready for Review, Ready for Merge

#82 Copy paste error p2
  src/algorithms/hidden_markov_model_impl.py
  src/preprocessing/hmm_preprocessor_impl.py
Labels: Ready for Review, Ready for Merge

#86 setting up communication with BFT
  .github/workflows/test.yml
  .gitignore
  .idea/algorithmic-trading.iml
  .idea/modules.xml
  .idea/vcs.xml
  Makefile
  README.md
  pyproject.toml
  requirements.txt
  uwqsc_algorithmic_trading/__init__.py
  uwqsc_algorithmic_trading/interfaces/__init__.py
  uwqsc_algorithmic_trading/interfaces/algorithms/__init__.py
  uwqsc_algorithmic_trading/interfaces/algorithms/algorithm_interface.py
  uwqsc_algorithmic_trading/interfaces/preprocessing/__init__.py
  uwqsc_algorithmic_trading/interfaces/preprocessing/preprocessor_interface.py
  uwqsc_algorithmic_trading/interfaces/sample_interface.py
  uwqsc_algorithmic_trading/src/__init__.py
  uwqsc_algorithmic_trading/src/algorithms/__init__.py
  uwqsc_algorithmic_trading/src/algorithms/hidden_markov_model_impl.py
  uwqsc_algorithmic_trading/src/algorithms/simple_moving_average_impl.py
  uwqsc_algorithmic_trading/src/common/__init__.py
  uwqsc_algorithmic_trading/src/common/config.py
  uwqsc_algorithmic_trading/src/common/data_collection.py
  uwqsc_algorithmic_trading/src/preprocessing/__init__.py
  uwqsc_algorithmic_trading/src/preprocessing/hmm_preprocessor_impl.py
  uwqsc_algorithmic_trading/src/preprocessing/sma_preprocessor_impl.py
  uwqsc_algorithmic_trading/src/sample_impl.py
  uwqsc_algorithmic_trading/tests/__init__.py
  uwqsc_algorithmic_trading/tests/algorithms/__init__.py
  uwqsc_algorithmic_trading/tests/algorithms/hidden_markov_model_impl_test.py
  uwqsc_algorithmic_trading/tests/algorithms/simple_moving_average_impl_test.py
  uwqsc_algorithmic_trading/tests/common/__init__.py
  uwqsc_algorithmic_trading/tests/common/data_collection_test.py
  uwqsc_algorithmic_trading/tests/preprocessing/__init__.py
  uwqsc_algorithmic_trading/tests/preprocessing/hmm_preprocessor_impl_test.py
  uwqsc_algorithmic_trading/tests/preprocessing/sma_preprocessor_impl_test.py
  uwqsc_algorithmic_trading/tests/sample_test.py
Labels: Ready for Review, Ready for Merge

#62 Added my name to the file
  member_list.txt
Labels: Ready for Merge

#90 Update member_list.txt
  member_list.txt
Labels: Ready for Review, Ready for Merge

#84 Implement HMM trade execution and add unit test
  .vscode/settings.json
  uwqsc_algorithmic_trading/src/algorithms/hidden_markov_model_impl.py
  uwqsc_algorithmic_trading/tests/algorithms/hidden_markov_model_impl_test.py
Labels: Ready for Review, Ready for Merge

#85 Implemented remove_duplicate_timestamps in HMMPreprocessorImpl class
  uwqsc_algorithmic_trading/src/preprocessing/hmm_preprocessor_impl.py
  uwqsc_algorithmic_trading/tests/preprocessing/hmm_preprocessor_impl_test.py
Labels: Ready for Merge

#93 Make SMA compatible with BTF
  .idea/algorithmic-trading.iml
  .idea/misc.xml
  pyproject.toml
  requirements.txt
  uwqsc_algorithmic_trading/interfaces/algorithms/algorithm_interface.py
  uwqsc_algorithmic_trading/interfaces/preprocessing/preprocessor_interface.py
  uwqsc_algorithmic_trading/src/algorithms/hidden_markov_model_impl.py
  uwqsc_algorithmic_trading/src/algorithms/simple_moving_average_impl.py
  uwqsc_algorithmic_trading/src/preprocessing/hmm_preprocessor_impl.py
  uwqsc_algorithmic_trading/src/preprocessing/sma_preprocessor_impl.py
  uwqsc_algorithmic_trading/tests/algorithms/hidden_markov_model_impl_test.py
  uwqsc_algorithmic_trading/tests/algorithms/simple_moving_average_impl_test.py
  uwqsc_algorithmic_trading/tests/preprocessing/hmm_preprocessor_impl_test.py
  uwqsc_algorithmic_trading/tests/preprocessing/sma_preprocessor_impl_test.py
Labels: Ready for Review, Ready for Merge

#96 topic/#27 - added Sumaiya Mayisha Shahadot to member list
  member_list.txt
Labels: Ready for Review, Ready for Merge

#87 Implement HMMPreProcessorImpl's missing_values
  uwqsc_algorithmic_trading/src/preprocessing/hmm_preprocessor_impl.py
  uwqsc_algorithmic_trading/tests/preprocessing/hmm_preprocessor_impl_test.py
Labels: Ready for Review, Ready for Merge
